dist: xenial
language: java

node_js:
  - "10"

env:
  global:
    - SONATYPE_USERNAME=ph@phloc.com
    - secure: "bGy5zCV41o8cG0sNX9SH0ALxTk2BJwfB6mzFvaNCXZHVLHaaRoiVBNy+ovlut5AVsYJtX1nCaOnv65+6tPd6J5QYk
sNxRwIUNqyHJQV83g5jcce9lPlrpO/sfpiSISq2PtRMjlqPq/favnNlIVu6dWJ4j8jP6rM6rqnacACwpqws668uMDxUnRhdh0Ad2
ds7FXB/fP4iYoo34B9AaGGkuoryBdfeWc92n8ijj96E7A5klySYMQmcaQ9sOYyv5Sw5Tu7QwA43MzFlTpsV5Y0QEn3F+8XzPJccz
IO8GIAOmQKHSd5pHZIImk/dgPkCXgTS+QNHe5iY6Lv44DzONQ4RosvA4SXW9xEaDncNgMxecm+zKr6u2ttTS1/6ZFRLCz6b1LguQ
vCpK+xj0KVW09t8Kwif0f0buTU5k9KR7QdL9/7YTy0ZRLZpLiZcXhi9UxQX2+qULc/VR1J9ahQZLUw9P8YijUI//YRalAGsIdXds
Kda356zKNHhu/x04SR7PjmbSN8LUmiPZ2yh2F/ZCekDdUygdgsXWcsxf8LJ/9DgTRoXA5e3ZgNbthM5iAcGAwBEFGGOZZPmrOPQh
51Arcl+fDNPOxN84o18L0JVawc83mgLNrk3TBZxofom0zQyp4KUrWiQT7Rb0o2Jvumo0t6YjAUCCEMrvp7fobzjUcbL9OA="

addons:
  sonarcloud:
    organization: "phax-github"
    token:
      secure: "JFJ2DS5ntFKdosS6z9Bz2DNrqJjk3NJXMf5l6pmyKpr/B9ugHjEivxO2u3qynN658YS+L83Vt8CxXsYfeoQ0Oyrktk7tCKlRh5aK5uu6WwRJRCYdoqKGmwD03EMwjw0PA9SDFXgl5T4ayWER5Wke3
1YwQFPgxyRKgVKN/Yf/X/JjVd6FSfnmrpRLMD2h4gebheMmRzCxcKfajLp6o5GYi2EocYisbeJSxl/jmWb2NIWJVJV2YC/3TlSoDGRygMcLtt6bUqqVB1MhN9+RRqEomiTGLtVf20uU9GrUfUCVD3JJl7cF0T5GH
X9dYwpRUTKdHIXbMHjjkV3sRi3JlZJAi7FhrwOXGcinwfArj8QbCf0Fx6Sqix3Ya5Dl6+aXbYrZKXNLQxF9/xq8oQGLAHXCuIqTBCQ9KPtus+CmMUIbdYxR6lwAlotGN75B8iDXiR0LDbGmevQZiLuJjaZ4inbqt
MLv14yqhf/ZtyHX2NXZes5ha+9aqzxHPWPovN6iSjwlTCw6bDiLZzgUvXdDR+fG8u1vTC24f9LvghDUgxVjS81VMXekAnzOmRCQTR8ZQltWXEzj5XdkkQOTi4B9eRFG9E6ECCSksUL+4IyZSBdzHWy2G01/0kPyv
Vcf9x7gvMvHzQ3Au3BuASef7bO3BSgn59gqgiioDBB2ljnQbhWGrug="

install:
#  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -U -P jdeps
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -U

cache:
  directories:
    - $HOME/.m2

branches:
  only:
    - master

jobs:
  include:
    - stage: test
      jdk: openjdk8
      script:
        - mvn test -B
      after_success:
        - mvn deploy --settings travis-settings.xml -DskipTests=true -B -P travis-deploy
    - stage: test
      jdk: openjdk11
      script:
        - mvn test -B -P coverage sonar:sonar
      after_success:
        - bash <(curl -s https://codecov.io/bash)
    - stage: test
      jdk: openjdk14
      script:
        - mvn test -B
