/*
 * Copyright (C) 2014-2025 Philip Helger (www.helger.com)
 * philip[at]helger[dot]com
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.helger.photon.core.buildinfo;

import java.lang.annotation.Documented;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.time.LocalDateTime;
import java.util.Map;

import org.jspecify.annotations.NonNull;
import org.jspecify.annotations.Nullable;

import com.helger.annotation.Nonnegative;
import com.helger.annotation.style.ReturnsMutableCopy;
import com.helger.base.enforce.ValueEnforcer;
import com.helger.base.tostring.ToStringGenerator;
import com.helger.collection.commons.CommonsHashMap;
import com.helger.collection.commons.ICommonsMap;
import com.helger.datetime.helper.PDTFactory;
import com.helger.io.resource.IReadableResource;
import com.helger.typeconvert.trait.IGetterByKeyTrait;
import com.helger.xml.microdom.util.XMLMapHandler;

/**
 * This class allows you to read the buildinfo.xml files generated by the
 * buildinfo-maven-plugin.
 *
 * @author Philip Helger
 */
public final class BuildInfo implements IGetterByKeyTrait <String>
{
  /**
   * The default filename as stored in the JAR files.
   */
  public static final String BUILDINFO_FILENAME_XML = "META-INF/buildinfo.xml";

  /**
   * Indicate that certain fields are only available from V2
   *
   * @author Philip Helger
   */
  @Retention (RetentionPolicy.SOURCE)
  @Documented
  public @interface SinceBuildInfoV2
  {}

  private static final String PREFIX_SYSPROPERTY = "systemproperty.";
  private static final String PREFIX_ENVVAR = "envvar.";

  private final ICommonsMap <String, String> m_aMap;
  private final int m_nVersion;
  private final ICommonsMap <String, String> m_aSysProperties = new CommonsHashMap <> ();
  private final ICommonsMap <String, String> m_aEnvVars = new CommonsHashMap <> ();

  public BuildInfo (@NonNull final ICommonsMap <String, String> aMap)
  {
    m_aMap = ValueEnforcer.notNull (aMap, "Map");
    m_nVersion = getAsInt ("buildinfo.version", 0);
    if (m_nVersion < 1)
      throw new IllegalArgumentException ("The passed map is not a buildinfo map!");

    // Extract all system properties and env vars
    for (final Map.Entry <String, String> aEntry : aMap.entrySet ())
    {
      final String sKey = aEntry.getKey ();
      if (sKey.startsWith (PREFIX_SYSPROPERTY))
        m_aSysProperties.put (sKey.substring (PREFIX_SYSPROPERTY.length ()), aEntry.getValue ());
      else
        if (sKey.startsWith (PREFIX_ENVVAR))
          m_aEnvVars.put (sKey.substring (PREFIX_ENVVAR.length ()), aEntry.getValue ());
    }
  }

  /**
   * @return The build info version number.
   */
  @Nonnegative
  public int getVersion ()
  {
    return m_nVersion;
  }

  /**
   * Get a string property.
   *
   * @param sKey
   *        The key to retrieve
   * @return <code>null</code> if the key does not exist
   */
  @Nullable
  public String getValue (@Nullable final String sKey)
  {
    return m_aMap.get (sKey);
  }

  @NonNull
  public String getProjectGroupID ()
  {
    return getAsString ("project.groupid");
  }

  @NonNull
  public String getProjectArtifactID ()
  {
    return getAsString ("project.artifactid");
  }

  @NonNull
  public String getProjectVersion ()
  {
    return getAsString ("project.version");
  }

  @NonNull
  public String getProjectName ()
  {
    return getAsString ("project.name");
  }

  @NonNull
  public String getProjectPackaging ()
  {
    return getAsString ("project.packaging");
  }

  @NonNull
  public String getParentProjectGroupID ()
  {
    return getAsString ("parentproject.groupid");
  }

  @NonNull
  public String getParentProjectArtifactID ()
  {
    return getAsString ("parentproject.artifactid");
  }

  @NonNull
  public String getParentProjectVersion ()
  {
    return getAsString ("parentproject.version");
  }

  @NonNull
  public String getParentProjectName ()
  {
    return getAsString ("parentproject.name");
  }

  @Nonnegative
  public int getBuildPluginCount ()
  {
    return getAsInt ("build.plugin.count", 0);
  }

  @NonNull
  public String getBuildPluginGroupID (@Nonnegative final int nIndex)
  {
    return getAsString ("build.plugin." + nIndex + ".groupid");
  }

  @NonNull
  public String getBuildPluginArtifactID (@Nonnegative final int nIndex)
  {
    return getAsString ("build.plugin." + nIndex + ".artifactid");
  }

  @NonNull
  public String getBuildPluginVersion (@Nonnegative final int nIndex)
  {
    return getAsString ("build.plugin." + nIndex + ".version");
  }

  @NonNull
  public String getBuildPluginConfiguration (@Nonnegative final int nIndex)
  {
    return getAsString ("build.plugin." + nIndex + ".configuration");
  }

  @SinceBuildInfoV2
  public String getBuildPluginKey (@Nonnegative final int nIndex)
  {
    return getAsString ("build.plugin." + nIndex + ".key");
  }

  @Nonnegative
  @SinceBuildInfoV2
  public int getDependencyCount ()
  {
    return getAsInt ("dependency.count", 0);
  }

  @NonNull
  @SinceBuildInfoV2
  public String getDependencyGroupID (@Nonnegative final int nIndex)
  {
    return getAsString ("dependency." + nIndex + ".groupid");
  }

  @NonNull
  @SinceBuildInfoV2
  public String getDependencyArtifactID (@Nonnegative final int nIndex)
  {
    return getAsString ("dependency." + nIndex + ".artifactid");
  }

  @NonNull
  @SinceBuildInfoV2
  public String getDependencyVersion (@Nonnegative final int nIndex)
  {
    return getAsString ("dependency." + nIndex + ".version");
  }

  @NonNull
  @SinceBuildInfoV2
  public String getDependencyType (@Nonnegative final int nIndex)
  {
    return getAsString ("dependency." + nIndex + ".type");
  }

  @Nullable
  @SinceBuildInfoV2
  public String getDependencyClassifier (@Nonnegative final int nIndex)
  {
    return getAsString ("dependency." + nIndex + ".classifier");
  }

  @NonNull
  @SinceBuildInfoV2
  public String getDependencyScope (@Nonnegative final int nIndex)
  {
    return getAsString ("dependency." + nIndex + ".scope");
  }

  @Nullable
  @SinceBuildInfoV2
  public String getDependencySystemPath (@Nonnegative final int nIndex)
  {
    return getAsString ("dependency." + nIndex + ".systempath");
  }

  @SinceBuildInfoV2
  public boolean isDependencyOptional (@Nonnegative final int nIndex)
  {
    return getAsBoolean ("dependency." + nIndex + ".optional");
  }

  /**
   * @param nIndex
   *        dependency index
   * @return <code><i>groupID</i>:<i>artifactid</i>:<i>type</i></code> - no
   *         version info!
   */
  @NonNull
  @SinceBuildInfoV2
  public String getDependencyManagementKey (@Nonnegative final int nIndex)
  {
    return getAsString ("dependency." + nIndex + ".managementkey");
  }

  // TODO add exclusions

  @NonNull
  public LocalDateTime getBuildDateTime ()
  {
    return PDTFactory.createLocalDateTime (getAsLong ("build.datetime.millis", 0));
  }

  @NonNull
  @ReturnsMutableCopy
  public ICommonsMap <String, String> getAllSystemProperties ()
  {
    return m_aSysProperties.getClone ();
  }

  @NonNull
  @ReturnsMutableCopy
  public ICommonsMap <String, String> getAllEnvVars ()
  {
    return m_aEnvVars.getClone ();
  }

  @Override
  public String toString ()
  {
    return new ToStringGenerator (this).append ("version", m_nVersion).append ("map", m_aMap).getToString ();
  }

  @Nullable
  public static BuildInfo createFromResource (@NonNull final IReadableResource aRes)
  {
    final ICommonsMap <String, String> aMap = XMLMapHandler.readMap (aRes);
    if (aMap == null)
      return null;
    return new BuildInfo (aMap);
  }
}
