--
-- ph-oton - baseline database schema for the JDBC backends of ph-oton-jdbc
-- Oracle 12c+
--
-- Copyright (C) 2014-2026 Philip Helger (www.helger.com)
-- Licensed under the Apache License, Version 2.0
--
-- This is the schema of ph-oton 10.3.x. V2 upgrades it to 10.4.0, so both
-- scripts run in order - a fresh installation simply migrates from an empty
-- database. See ../../README.md for details, caveats and the mapping of every
-- column to its source code constant.
--
-- The table names are the defaults. If the application passes a table name
-- customizer to the *ManagerJDBC constructors, adapt the names accordingly.
--

-- Notes for Oracle 12c+:
--   Oracle has no native BOOLEAN column type before 23ai, so NUMBER(1) is used.
--   Reading it back works, because ph-commons converts any Number to a boolean
--   via 'intValue () != 0'. Verify that your ojdbc driver binds a java.lang.Boolean
--   parameter to a NUMBER column - see docs/README.md.
--

-- Written by AuditorJDBC (ph-oton-audit / ph-oton-jdbc).
-- Append only. 'id' is a surrogate key that is never read by
-- AuditorJDBC - it exists so that the physical insertion order is
-- preserved and so that the table has a primary key at all, because
-- 'dt' and 'userid' may be recorded more than once.
CREATE TABLE audit (
  id         NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,           -- surrogate key, ensures the order of entry
  dt         TIMESTAMP NOT NULL,
  userid     VARCHAR2(40 CHAR) NOT NULL,                                -- GlobalIDFactory.STRING_ID_MAX_LENGTH
  actiontype VARCHAR2(10 CHAR) NOT NULL,                                -- EAuditActionType.MAX_ID_LENGTH
  success    NUMBER(1) NOT NULL,
  action     CLOB,                                                      -- JSON array
  CONSTRAINT pk_audit PRIMARY KEY (id)
);
CREATE INDEX idx_audit_dt ON audit (dt);

-- Written by LongRunningJobResultManagerJDBC.
-- 'job_data' contains the whole job result as XML.
-- 'id' is the globally unique ID of a single job execution.
-- V2 adds the 'job_type' column of ph-oton 10.4.0.
CREATE TABLE long_running_job (
  id       VARCHAR2(40 CHAR) NOT NULL,                                  -- GlobalIDFactory.STRING_ID_MAX_LENGTH
  start_dt TIMESTAMP NOT NULL,
  job_data CLOB NOT NULL,                                               -- XML
  CONSTRAINT pk_long_running_job PRIMARY KEY (id)
);
CREATE INDEX idx_lrj_start_dt ON long_running_job (start_dt);

-- Written by SystemMigrationManagerJDBC.
-- No primary key - a migration ID may be recorded several times,
-- e.g. once per failed and once per successful attempt.
CREATE TABLE sys_migration (
  migration_id VARCHAR2(256 CHAR) NOT NULL,                             -- ISystemMigrationManager.MIGRATION_ID_MAX_LENGTH
  execution_dt TIMESTAMP NOT NULL,
  success      NUMBER(1) NOT NULL,
  error_msg    CLOB
);
CREATE INDEX idx_sysmig_migration_id ON sys_migration (migration_id);

-- Written by SystemMessageManagerJDBC.
-- Holds at most one row - the manager updates without a WHERE clause
-- and only inserts if the update affected no row.
CREATE TABLE sys_message (
  messagetype VARCHAR2(1 CHAR) NOT NULL,                                -- ESystemMessageType ID is a single char
  lastupdate  TIMESTAMP,
  message     CLOB
);

-- Written by RoleManagerJDBC.
CREATE TABLE secrole (
  id             VARCHAR2(45 CHAR) NOT NULL,                            -- IRole.ROLE_ID_MAX_LENGTH
  creationdt     TIMESTAMP,
  creationuserid VARCHAR2(40 CHAR),
  lastmoddt      TIMESTAMP,
  lastmoduserid  VARCHAR2(40 CHAR),
  deletedt       TIMESTAMP,
  deleteuserid   VARCHAR2(40 CHAR),
  attrs          CLOB,                                                  -- JSON object
  name           VARCHAR2(255 CHAR) NOT NULL,                           -- IRole.ROLE_NAME_MAX_LENGTH
  description    CLOB,
  CONSTRAINT pk_secrole PRIMARY KEY (id)
);

-- Written by UserGroupManagerJDBC.
-- 'userids' and 'roleids' are JSON arrays of the contained IDs -
-- there are deliberately no foreign keys to secuser / secrole.
CREATE TABLE secusergroup (
  id             VARCHAR2(45 CHAR) NOT NULL,                            -- IUserGroup.USER_GROUP_ID_MAX_LENGTH
  creationdt     TIMESTAMP,
  creationuserid VARCHAR2(40 CHAR),
  lastmoddt      TIMESTAMP,
  lastmoduserid  VARCHAR2(40 CHAR),
  deletedt       TIMESTAMP,
  deleteuserid   VARCHAR2(40 CHAR),
  attrs          CLOB,                                                  -- JSON object
  name           VARCHAR2(255 CHAR) NOT NULL,                           -- IUserGroup.USER_GROUP_NAME_MAX_LENGTH
  description    CLOB,
  userids        CLOB,                                                  -- JSON array
  roleids        CLOB,                                                  -- JSON array
  CONSTRAINT pk_secusergroup PRIMARY KEY (id)
);

-- Written by UserManagerJDBC.
-- 'loginname' is only unique among the non-deleted users, and that
-- uniqueness is enforced in Java - hence no UNIQUE constraint here.
CREATE TABLE secuser (
  id             VARCHAR2(20 CHAR) NOT NULL,                            -- IUser.USER_ID_MAX_LENGTH
  creationdt     TIMESTAMP,
  creationuserid VARCHAR2(40 CHAR),
  lastmoddt      TIMESTAMP,
  lastmoduserid  VARCHAR2(40 CHAR),
  deletedt       TIMESTAMP,
  deleteuserid   VARCHAR2(40 CHAR),
  attrs          CLOB,                                                  -- JSON object
  loginname      VARCHAR2(200 CHAR) NOT NULL,                           -- IUser.LOGIN_NAME_MAX_LENGTH
  email          VARCHAR2(200 CHAR),                                    -- IUser.EMAIL_ADDRESS_MAX_LENGTH
  pwalgo         VARCHAR2(100 CHAR) NOT NULL,                           -- PasswordHash.ALGORITHM_NAME_MAX_LENGTH
  pwsalt         CLOB,                                                  -- not limited in code
  pwhash         CLOB NOT NULL,                                         -- not limited in code
  firstname      CLOB,                                                  -- not limited in code
  lastname       CLOB,                                                  -- not limited in code
  description    CLOB,
  locale         VARCHAR2(20 CHAR),                                     -- IUser.DESIRED_LOCALE_MAX_LENGTH
  lastlogindt    TIMESTAMP,
  logincount     NUMBER(10) NOT NULL,
  failedlogins   NUMBER(10) NOT NULL,
  disabled       NUMBER(1) NOT NULL,
  CONSTRAINT pk_secuser PRIMARY KEY (id)
);
CREATE INDEX idx_secuser_loginname ON secuser (loginname);

-- Written by UserTokenManagerJDBC.
-- 'accesstokens' is a JSON array of all access tokens of this user token.
CREATE TABLE secusertoken (
  id             VARCHAR2(45 CHAR) NOT NULL,                            -- IUserToken.USER_TOKEN_ID_MAX_LENGTH
  creationdt     TIMESTAMP,
  creationuserid VARCHAR2(40 CHAR),
  lastmoddt      TIMESTAMP,
  lastmoduserid  VARCHAR2(40 CHAR),
  deletedt       TIMESTAMP,
  deleteuserid   VARCHAR2(40 CHAR),
  attrs          CLOB,                                                  -- JSON object
  accesstokens   CLOB,                                                  -- JSON array
  userid         VARCHAR2(20 CHAR),                                     -- IUser.USER_ID_MAX_LENGTH
  description    CLOB,
  CONSTRAINT pk_secusertoken PRIMARY KEY (id)
);
