/**
 * Copyright (C) 2014-2015 Philip Helger (www.helger.com)
 * philip[at]helger[dot]com
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.helger.html.hc.html;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;

import java.util.ArrayList;

import org.junit.Test;

import com.helger.commons.collections.CollectionHelper;
import com.helger.html.hc.IHCNode;
import com.helger.html.hc.IHCNodeBuilder;

/**
 * Test class for class {@link HCAbbr} This file is automatically generated from
 * com.helger.html.supplementary.main.MainCreateHCClasses so DO NOT EDIT!
 *
 * @author Philip Helger
 */
public final class HCAbbrTest
{
  @Test
  public void testCreate ()
  {
    assertFalse (new HCAbbr ().hasChildren ());
    assertEquals (0, HCAbbr.create ((IHCNodeBuilder) null).getChildCount ());
    assertEquals (0, HCAbbr.create ((IHCNodeBuilder) null, (IHCNodeBuilder) null).getChildCount ());
    assertEquals (1, HCAbbr.create ("Text").getChildCount ());
    assertEquals (0, HCAbbr.create ((String) null).getChildCount ());
    assertEquals (1, HCAbbr.create (HCB.create ("Bold")).getChildCount ());
    assertEquals (0, HCAbbr.create ((IHCNode) null).getChildCount ());
    assertEquals (3, HCAbbr.create ("Hallo", "Welt", "!!!").getChildCount ());
    assertEquals (0, HCAbbr.create (new String [0]).getChildCount ());
    assertEquals (0, HCAbbr.create ((String []) null).getChildCount ());
    assertEquals (2, HCAbbr.create (HCB.create ("Bold"), HCI.create ("Italic")).getChildCount ());
    assertEquals (0, HCAbbr.create (new IHCNode [0]).getChildCount ());
    assertEquals (0, HCAbbr.create ((IHCNode []) null).getChildCount ());
    assertEquals (2, HCAbbr.create (CollectionHelper.newList (HCB.create ("Bold"), HCI.create ("Italic")))
                           .getChildCount ());
    assertEquals (0, HCAbbr.create (new ArrayList <IHCNode> ()).getChildCount ());
  }
}
